#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-cnrancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

IMAGE=${REPO}/rancher-auditlog-allinone:${TAG}
DOCKERFILE=package/all-in-one/Dockerfile

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}