#!/bin/bash
set -e

cd $(dirname $0)/..

echo "Running validation"

PACKAGES="$(go list ./...)"

echo "Running: go vet"
go vet ${PACKAGES}

if ! command -v golangci-lint; then
    echo "Skipping: golangci-lint not available"
else
    echo "Running: golangci-lint"
    golangci-lint run
fi

echo "Running: go fmt"
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"